### ISSUE TITLE
spawn ENOENT on Mac (spaces in paths?)

### ISSUE THREAD

**Issue by Zeipt** [foreverjs/forever-monitor#90] opened 2015-01-05 01:39 UTC
My node-binary and child-script are in the "/Users/user/Library/Application Support/Firefox/..."
All are accessible and working directly with terminal. But spawn with forever-monitor always gives error:

event.js:72
throw er; // Unhandled 'error' event
Error: spawn ENOENT
at errnoException (child_process.js:1011:11)
at Process.ChildProcess._handle.onexit (child_process.js:802:34)

forever-monitor 1.5.2
nodejs 0.10.35
OSX 10.8.2

**Comment by indexzero** [comment] 2015-07-23 13:15
Sounds like a bug.

**Comment by indexzero** [comment] 2015-07-23 13:18
Duplicate of #35

**Closed by indexzero** 2015-07-23 13:18 UTC
Labels: bug
